name: auto-tagging

#https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-describe.html
on:
  pull_request:
    branches:
#      - master
      - test**
    types:
#      - closed
      - opened
      - synchronize

#    if: github.event.pull_request.merged == true
jobs:
  auto-tagging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: get latest tag
        run: |
          git fetch origin test/tagging:test/tagging
          git checkout test/tagging
          latest_tag_version=$(git describe --tags --abbrev=0)
          echo "latest tag version is $latest_tag_version"
          echo "LATEST_TAG_VERSION=${latest_tag_version}" >> $GITHUB_ENV

      - name: major version up
        if: ${{ github.event.pull_request.labels.*.name == 'major' }}
        run: |
          current_tag=$(echo $LATEST_TAG_VERSION | sed 's/v//')
          major=${echo $current_tag | cut -d. -f1)
          minor=$(echo $current_tag | cut -d. -f2)
          patch=$(echo $current_tag | cut -d. -f3)
         
          new_tag=$((${major} + 1)).${minor}.${patch}
          
          echo "new tag version is $new_tag"