name: auto-tagging

#https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-describe.html
on:
  pull_request:
    branches:
#      - master
      - test**
    types:
#      - closed
      - opened
      - synchronize

#    if: github.event.pull_request.merged == true
jobs:
  auto-tagging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: get latest tag
        run: |
          git fetch origin test/tagging:test/tagging
          git checkout test/tagging
          latest_tag_version=$(git describe --tags --abbrev=0)
          echo "latest tag version is $latest_tag_version"
          echo "LATEST_TAG_VERSION=${latest_tag_version}" >> $GITHUB_ENV

      - name: set default tag version
        run: |
          current_tag=$(echo $LATEST_TAG_VERSION | sed 's/v//')
          
          echo "major=$(echo $current_tag | cut -d. -f1)" >> $GITHUB_ENV
          echo "minor=$(echo $current_tag | cut -d. -f2)" >> $GITHUB_ENV
          echo "patch=$(echo $current_tag | cut -d. -f3)" >> $GITHUB_ENV

      - name: major version up
        if: contains(github.event.pull_request.labels.*.name, 'major')
        run: |
          new_major=$((major + 1))
          echo "new major is $new_major
          
          echo "major=${new_major}" >> $GITHUB_ENV
          echo "new major version is $major"

      - name: minor version up
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: |
          new_minor=$((minor + 1))
          echo "new minor is $new_minor
          
          echo "minor=$new_minor" >> $GITHUB_ENV
          echo "new minor version is $minor"

      - name: patch version up
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        run: |
          new_patch=$((patch + 1))
          echo "new patch is $new_patch
          
          echo "patch=${new_patch}" >> $GITHUB_ENV
          echo "new patch version is $patch"

      - name: print all version
        run: echo "update version is v$major.$minor.$patch"