name: auto-tagging

#https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-describe.html
on:
  pull_request:
    branches:
#      - master
      - test**
    types:
#      - closed
      - opened
      - synchronize

#    if: github.event.pull_request.merged == true
jobs:
  auto-tagging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: get latest tag
        run: |
          git checkout test/tagging
          git describe --tags --abbrev=0