name: Android CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "feature**", "hotfix**", "release**", "develop**", "master" ]

jobs:
  common_setup:
    uses: ./.github/workflows/common-setup.yaml
    secrets: inherit

  build:
    needs: common_setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Download common setup files
        uses: actions/download-artifact@v4
        with:
          name: common-setup-files

      - name: Build with Gradle
        run: ./gradlew assembleDebug
