name: Android CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "feature**", "hotfix**", "release**", "develop", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle Packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Create Google Json file
        run: cat /home/runner/work/Dorabangs_Android/Dorabangs_Android/app/google-services.json | base64
        
      - name: Putting Json data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/Dorabangs_Android/Dorabangs_Android/app/google-services.json
        
      - name: Access SERVER_BASE_URL
        run:  |
          echo server_base_url=\"$API_KEY\" > local.properties
        shell: bash
        env: 
          API_KEY: ${{ secrets.SERVER_BASE_URL }}
          
      - name: Build with Gradle
        run: ./gradlew assembleDebug
