name: Android CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "feature**", "hotfix**", "release**", "develop**", "master" ]

jobs:
  common_setup:
    uses: mash-up-kr/Dorabangs_Android/.github/workflows/common-setup.yaml@cd75c2a956f76c1c39592331dfa84e4938e02791

  build:
    needs: common_setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle
      - name: Download common setup files
        uses: actions/download-artifact@v4
        with:
          name: common-setup-files
          path: ${GITHUB_WORKSPACE}/app

      - name: Build with Gradle
        run: ./gradlew assembleDebug
